# Libraries

In [ ]:
# Libraries

import numpy as np
import pandas as pd
import re

!pip install ktrain
import keras
import ktrain
from ktrain import text

# Functions

In [ ]:
# test dataset - tweets - the sentences are merged into a single tweet

def dataframe_full_text(dataframe):
  del dataframe['Unnamed: 0']
  del dataframe['sentence']
  lines, columns = dataframe.shape

  if columns == 2:
    df_final_test = dataframe
    df_final_test.columns = ['sentence','target']

  if columns > 2:
    target = dataframe['target']
    del dataframe['target']
    lines, columns = dataframe.shape
    array_test = np.array(dataframe)
    array_empty = []
    
    for line in range(lines):
      final_list = []
      for column in range(0,columns-1,2):
        string = str(array_test[line][column])
        if string != '' and string != '??' and string != 'nan':
          if '1.0' in string:
            string = re.sub(r'1.0','1',string)
          if '2.0' in string:
            string = re.sub(r'2.0','2',string)
          if '3.0' in string:
            string = re.sub(r'3.0','3',string)
          if '4.0' in string:
            string = re.sub(r'4.0','4',string)
          if '5.0' in string:
            string = re.sub(r'5.0','5',string)
          final_list.append(string)
      final_string = ' '.join(final_list)
      array_empty.append(final_string)

    df_string_concat = pd.DataFrame(array_empty)
    df_final_test = pd.concat((df_string_concat, target), axis = 1)
    df_final_test.columns = ['sentence','target']

  return df_final_test

In [ ]:
# test dataset - sentences - the dataset comprises only sentences

def dataframe_sentences(dataframe):
  del dataframe['Unnamed: 0']
  del dataframe['sentence']
  lines, columns = dataframe.shape

  if columns == 2:
    df = dataframe

  if columns > 2:
    del dataframe['target']
    lines, columns = dataframe.shape
    array_test = np.array(dataframe)
    sentence_target_list = []
    
    for line in range(lines):
      for column in range(0,columns):
        string = str(array_test[line][column])

        if string != '' and string != '??' and string != 'nan' and string != 'NaN':
          if ((len(sentence_target_list) != 0) and ((sentence_target_list[-1] == '1') or (sentence_target_list[-1] == '2') or (sentence_target_list[-1] == '3') or (sentence_target_list[-1] == '4') or (sentence_target_list[-1] == '5')) and ((string != '1') or (string != '2') or (string != '3') or (string != '4') or (string != '5'))):
            if '1.0' in string:
              string = re.sub(r'1.0','1',string)
            if '2.0' in string:
              string = re.sub(r'2.0','2',string)
            if '3.0' in string:
              string = re.sub(r'3.0','3',string)
            if '4.0' in string:
              string = re.sub(r'4.0','4',string)
            if '5.0' in string:
              string = re.sub(r'5.0','5',string)
            sentence_target_list.append(string)
          if ((len(sentence_target_list) != 0) and ((sentence_target_list[-1] != '1') or (sentence_target_list[-1] != '2') or (sentence_target_list[-1] != '3') or (sentence_target_list[-1] != '4') or (sentence_target_list[-1] != '5')) and ((string == '1') or (string == '2') or (string == '3') or (string == '4') or (string == '5'))):
            if '1.0' in string:
              string = re.sub(r'1.0','1',string)
            if '2.0' in string:
              string = re.sub(r'2.0','2',string)
            if '3.0' in string:
              string = re.sub(r'3.0','3',string)
            if '4.0' in string:
              string = re.sub(r'4.0','4',string)
            if '5.0' in string:
              string = re.sub(r'5.0','5',string)
            sentence_target_list.append(string)
          if len(sentence_target_list) == 0:
            sentence_target_list.append(string)

    length = len(sentence_target_list)
    lines = int(length/2)
    columns = 2
    list_to_array = np.array(sentence_target_list)
    final_array = np.reshape(list_to_array, (lines, columns))
    df = pd.DataFrame(final_array)
  df.columns = ['sentence','target']

  return df

In [ ]:
# classification - one-hot

def one_hot(dataframe):
  list_01 = [1,0,0,0,0]
  list_02 = [0,1,0,0,0]
  list_03 = [0,0,1,0,0]
  list_04 = [0,0,0,1,0]
  list_05 = [0,0,0,0,1]
  lines, columns = dataframe.shape
  df_array = np.array(dataframe)
  one_hot_vectors = []

  for i in range(lines):
    if df_array[i][1] == 1 or df_array[i][1] == 1.0:
      one_hot_vectors.append(list_01)
    elif df_array[i][1] == 2 or df_array[i][1] == 2.0:
      one_hot_vectors.append(list_02)
    elif df_array[i][1] == 3 or df_array[i][1] == 3.0:
      one_hot_vectors.append(list_03)
    elif df_array[i][1] == 4 or df_array[i][1] == 4.0:
      one_hot_vectors.append(list_04)
    elif df_array[i][1] == 5 or df_array[i][1] == 5.0:
      one_hot_vectors.append(list_05)

  one_hot_array = np.array(one_hot_vectors).reshape(len(one_hot_vectors),5)
  one_hot_dataframe = pd.DataFrame(one_hot_array)
  del dataframe['target']
  df_one_hot = pd.concat((dataframe,one_hot_dataframe), axis = 1)
  df_one_hot.columns = ['sentence', '01','02','03','04','05']

  return df_one_hot

# Loading files

In [ ]:
# Loading files to dataframe

# train dataset
df_train = one_hot(dataframe_sentences(pd.read_excel('train_bert.xlsx')))

# test dataset
df_test_sentence = one_hot(dataframe_sentences(pd.read_excel('test_bert.xlsx')))
df_test_tweet = one_hot(dataframe_full_text(pd.read_excel('test_bert.xlsx')))

# Test 01

In [ ]:
# Create vectors https://github.com/amaiya/ktrain/blob/master/ktrain/text/data.py
(x_train_00, y_train_00), (x_test_sentence, y_test_sentence), preproc = text.texts_from_df(df_train, text_column='sentence',
                                                                                      label_columns=['01','02','03','04','05'],
                                                                                      maxlen=64,
                                                                                      preprocess_mode = 'bert',
                                                                                      lang = None,
                                                                                      ngram_range=1,
                                                                                      val_df = df_test_sentence,
                                                                                      random_state = 42
                                                                                      )

learn_bert_test_01 = ktrain.get_learner(text.text_classifier('bert', (x_train_00, y_train_00) , preproc=preproc), 
                             train_data=(x_train_00, y_train_00), 
                             val_data=(x_test_sentence, y_test_sentence), batch_size = 5
                             )

learn_bert_test_01.fit_onecycle(0.01,3)

learn_bert_test_01.validate()

downloading pretrained BERT model (multi_cased_L-12_H-768_A-12.zip)...
[██████████████████████████████████████████████████]
extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: pt


Is Multi-Label? False
preprocessing test...
language: pt


Is Multi-Label? False
maxlen is 64
done.


begin training using onecycle policy with max lr of 0.01...
Epoch 1/3
234/234 [==============================] - 1147s 5s/step - loss: 1.6864 - accuracy: 0.3316 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 2/3
234/234 [==============================] - 1145s 5s/step - loss: 2.5595 - accuracy: 0.3538 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 3/3
234/234 [==============================] - 1147s 5s/step - loss: 1.6179 - accuracy: 0.3265 - val_loss: nan - val_accuracy: 0.0000e+00
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     218.0
           2       0.00      0.00      0.00       0.0

    accuracy                           0.00     218.0
   macro avg       0.00      0.00      0.00     218.0
weighted avg       0.00      0.00      0.00     218.0



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[  0, 218],
       [  0,   0]])

# Test 02

In [ ]:
(x_train_01, y_train_01), (x_test_tweet, y_test_tweet), preproc01 = text.texts_from_df(df_train, text_column = 'sentence',
                                                                                    label_columns = ['01','02','03','04','05'],
                                                                                    maxlen = 64, 
                                                                                    preprocess_mode = 'bert',
                                                                                    lang = None,
                                                                                    ngram_range = 1,
                                                                                    val_df = df_test_tweet,
                                                                                    random_state = 42
                                                                                    )

learn_bert_test_02 = ktrain.get_learner(text.text_classifier('bert', (x_train_01, y_train_01) , preproc = preproc01), 
                             train_data = (x_train_01, y_train_01), 
                             val_data = (x_test_tweet, y_test_tweet), batch_size = 10
                             )

learn_bert_test_02.fit_onecycle(0.01,3)

learn_bert_test_02.validate()

preprocessing train...
language: pt


Is Multi-Label? False
preprocessing test...
language: pt


Is Multi-Label? False
maxlen is 64
done.


begin training using onecycle policy with max lr of 0.01...
Epoch 1/3
117/117 [==============================] - 961s 8s/step - loss: 1.6794 - accuracy: 0.3239 - val_loss: 2.7086 - val_accuracy: 0.0780
Epoch 2/3
117/117 [==============================] - 967s 8s/step - loss: 1.8557 - accuracy: 0.3316 - val_loss: 1.6847 - val_accuracy: 0.3670
Epoch 3/3
117/117 [==============================] - 956s 8s/step - loss: 1.4768 - accuracy: 0.3291 - val_loss: 1.5587 - val_accuracy: 0.0780
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00        80
           2       0.08      1.00      0.14        17
           3       0.00      0.00      0.00        95
           4       0.00      0.00      0.00        25

    accuracy                           0.08       218
   macro avg       0.02      0.20      0.03       218
weighted avg       0.01      0.08    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[ 0,  0,  1,  0,  0],
       [ 0,  0, 80,  0,  0],
       [ 0,  0, 17,  0,  0],
       [ 0,  0, 95,  0,  0],
       [ 0,  0, 25,  0,  0]])

# Loading files

In [ ]:
# Loading files to dataframe

# train dataset
df_train = one_hot(dataframe_sentences(pd.read_excel('train_bag.xlsx')))

# test dataset
df_test_sentence = one_hot(dataframe_sentences(pd.read_excel('test_bag.xlsx')))
df_test_tweet = one_hot(dataframe_full_text(pd.read_excel('test_bag.xlsx')))

# Test 03

In [ ]:
# Create vectors https://github.com/amaiya/ktrain/blob/master/ktrain/text/data.py
(x_train_00, y_train_00), (x_test_sentence, y_test_sentence), preproc = text.texts_from_df(df_train, text_column='sentence',
                                                                                      label_columns=['01','02','03','04','05'],
                                                                                      maxlen=64,
                                                                                      preprocess_mode = 'bert',
                                                                                      lang = None,
                                                                                      ngram_range=1,
                                                                                      val_df = df_test_sentence,
                                                                                      random_state = 42,
                                                                                      )

learn_bert_test_01 = ktrain.get_learner(text.text_classifier('bert', (x_train_00, y_train_00) , preproc=preproc), 
                             train_data=(x_train_00, y_train_00), 
                             val_data=(x_test_sentence, y_test_sentence), batch_size = 5
                             )

learn_bert_test_01.fit_onecycle(0.01,3)

learn_bert_test_01.validate()

downloading pretrained BERT model (multi_cased_L-12_H-768_A-12.zip)...
[██████████████████████████████████████████████████]
extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: pt


Is Multi-Label? False
preprocessing test...
language: pt


Is Multi-Label? False
maxlen is 64
done.


begin training using onecycle policy with max lr of 0.01...
Epoch 1/3
234/234 [==============================] - 1157s 5s/step - loss: 2.0354 - accuracy: 0.3060 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 2/3
234/234 [==============================] - 1148s 5s/step - loss: 2.5510 - accuracy: 0.3188 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 3/3
234/234 [==============================] - 1146s 5s/step - loss: 1.6353 - accuracy: 0.3137 - val_loss: nan - val_accuracy: 0.0000e+00
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     218.0
           2       0.00      0.00      0.00       0.0

    accuracy                           0.00     218.0
   macro avg       0.00      0.00      0.00     218.0
weighted avg       0.00      0.00      0.00     218.0



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[  0, 218],
       [  0,   0]])

# Test 04

In [ ]:
(x_train_01, y_train_01), (x_test_tweet, y_test_tweet), preproc01 = text.texts_from_df(df_train, text_column = 'sentence',
                                                                                    label_columns = ['01','02','03','04','05'],
                                                                                    maxlen = 64, 
                                                                                    preprocess_mode = 'bert',
                                                                                    lang = None,
                                                                                    ngram_range = 1,
                                                                                    val_df = df_test_tweet,
                                                                                    random_state = 42
                                                                                    )

learn_bert_test_02 = ktrain.get_learner(text.text_classifier('bert', (x_train_01, y_train_01) , preproc = preproc01), 
                             train_data = (x_train_01, y_train_01), 
                             val_data = (x_test_tweet, y_test_tweet), batch_size = 10
                             )

learn_bert_test_02.fit_onecycle(0.01,3)

learn_bert_test_02.validate()

preprocessing train...
language: pt


Is Multi-Label? False
preprocessing test...
language: pt


Is Multi-Label? False
maxlen is 64
done.


begin training using onecycle policy with max lr of 0.01...
Epoch 1/3
117/117 [==============================] - 959s 8s/step - loss: 1.9373 - accuracy: 0.3205 - val_loss: 1.8341 - val_accuracy: 0.3670
Epoch 2/3
117/117 [==============================] - 952s 8s/step - loss: 1.9886 - accuracy: 0.3060 - val_loss: 3.2257 - val_accuracy: 0.4358
Epoch 3/3
117/117 [==============================] - 959s 8s/step - loss: 1.4113 - accuracy: 0.3419 - val_loss: 1.6079 - val_accuracy: 0.4358
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00        80
           2       0.00      0.00      0.00        17
           3       0.44      1.00      0.61        95
           4       0.00      0.00      0.00        25

    accuracy                           0.44       218
   macro avg       0.09      0.20      0.12       218
weighted avg       0.19      0.44    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[ 0,  0,  0,  1,  0],
       [ 0,  0,  0, 80,  0],
       [ 0,  0,  0, 17,  0],
       [ 0,  0,  0, 95,  0],
       [ 0,  0,  0, 25,  0]])