# Libraries

In [ ]:
# Libraries

import numpy as np
import pandas as pd
import re

!pip install ktrain
import keras
import ktrain
from ktrain import text

# Functions

In [ ]:
# test dataset - tweets - the sentences are merged into a single tweet

def dataframe_full_text(dataframe):
  del dataframe['Unnamed: 0']
  del dataframe['sentence']
  lines, columns = dataframe.shape

  if columns == 2:
    df_final_test = dataframe
    df_final_test.columns = ['sentence','target']

  if columns > 2:
    target = dataframe['target']
    del dataframe['target']
    lines, columns = dataframe.shape
    array_test = np.array(dataframe)
    array_empty = []
    
    for line in range(lines):
      final_list = []
      for column in range(0,columns-1,2):
        string = str(array_test[line][column])
        if string != '' and string != '??' and string != 'nan' and string != 'NaN':
          if '1.0' in string:
            string = re.sub(r'1.0','1',string)
          if '2.0' in string:
            string = re.sub(r'2.0','2',string)
          if '3.0' in string:
            string = re.sub(r'3.0','3',string)
          if '4.0' in string:
            string = re.sub(r'4.0','4',string)
          if '5.0' in string:
            string = re.sub(r'5.0','5',string)
          final_list.append(string)
      final_string = ' '.join(final_list)
      array_empty.append(final_string)

    df_string_concat = pd.DataFrame(array_empty)
    df_final_test = pd.concat((df_string_concat, target), axis = 1)
    df_final_test.columns = ['sentence','target']

  return df_final_test

In [ ]:
# test dataset - sentences - the dataset comprises only sentences

def dataframe_sentences(dataframe):
  del dataframe['Unnamed: 0']
  del dataframe['sentence']
  lines, columns = dataframe.shape

  if columns == 2:
    df = dataframe

  if columns > 2:
    del dataframe['target']
    lines, columns = dataframe.shape
    array_test = np.array(dataframe)
    sentence_target_list = []
    
    for line in range(lines):
      for column in range(0,columns):
        string = str(array_test[line][column])
        if '1.0' in string:
          string = re.sub(r'1.0','1',string)
        if '2.0' in string:
          string = re.sub(r'2.0','2',string)
        if '3.0' in string:
          string = re.sub(r'3.0','3',string)
        if '4.0' in string:
          string = re.sub(r'4.0','4',string)
        if '5.0' in string:
          string = re.sub(r'5.0','5',string)

        if string != '' and string != '??' and string != 'nan' and string != 'NaN':
          if ((len(sentence_target_list) != 0) and ((sentence_target_list[-1] == '1') or (sentence_target_list[-1] == '2') or (sentence_target_list[-1] == '3') or (sentence_target_list[-1] == '4') or (sentence_target_list[-1] == '5')) and ((string != '1') or (string != '2') or (string != '3') or (string != '4') or (string != '5'))):
            sentence_target_list.append(string)
          if ((len(sentence_target_list) != 0) and ((sentence_target_list[-1] != '1') or (sentence_target_list[-1] != '2') or (sentence_target_list[-1] != '3') or (sentence_target_list[-1] != '4') or (sentence_target_list[-1] != '5')) and ((string == '1') or (string == '2') or (string == '3') or (string == '4') or (string == '5'))):
            sentence_target_list.append(string)
          if len(sentence_target_list) == 0:
            sentence_target_list.append(string)

    length = len(sentence_target_list)
    lines = int(length/2)
    columns = 2
    list_to_array = np.array(sentence_target_list)
    final_array = np.reshape(list_to_array, (lines, columns))
    df = pd.DataFrame(final_array)
  df.columns = ['sentence','target']

  return df

In [ ]:
# classification - one-hot

def one_hot(dataframe):
  list_01 = [1,0,0,0,0]
  list_02 = [0,1,0,0,0]
  list_03 = [0,0,1,0,0]
  list_04 = [0,0,0,1,0]
  list_05 = [0,0,0,0,1]
  lines, columns = dataframe.shape
  df_array = np.array(dataframe)
  one_hot_vectors = []

  for i in range(lines):
    if df_array[i][1] == 1 or df_array[i][1] == 1.0 or df_array[i][1] == '1' or df_array[i][1] == '1.0':
      one_hot_vectors.append(list_01)
    elif df_array[i][1] == 2 or df_array[i][1] == 2.0 or df_array[i][1] == '2' or df_array[i][1] == '2.0':
      one_hot_vectors.append(list_02)
    elif df_array[i][1] == 3 or df_array[i][1] == 3.0 or df_array[i][1] == '3' or df_array[i][1] == '3.0':
      one_hot_vectors.append(list_03)
    elif df_array[i][1] == 4 or df_array[i][1] == 4.0 or df_array[i][1] == '4' or df_array[i][1] == '4.0':
      one_hot_vectors.append(list_04)
    elif df_array[i][1] == 5 or df_array[i][1] == 5.0 or df_array[i][1] == '5' or df_array[i][1] == '5.0':
      one_hot_vectors.append(list_05)

  one_hot_array = np.array(one_hot_vectors).reshape(len(one_hot_vectors),5)
  one_hot_dataframe = pd.DataFrame(one_hot_array)
  del dataframe['target']
  df_one_hot = pd.concat((dataframe,one_hot_dataframe), axis = 1)
  df_one_hot.columns = ['sentence', '01','02','03','04','05']

  return df_one_hot

# Loading files

In [ ]:
# Loading files to dataframe

# train dataset
df_train = one_hot(dataframe_sentences(pd.read_excel('train_bag.xlsx')))
df_train_stemmer = one_hot(dataframe_sentences(pd.read_excel('train_bag_stemmer.xlsx')))

# test dataset
df_test_sentence = one_hot(dataframe_sentences(pd.read_excel('test_bag.xlsx')))
df_test_sentence_stemmer = one_hot(dataframe_sentences(pd.read_excel('test_bag_stemmer.xlsx')))
df_test_tweet = one_hot(dataframe_full_text(pd.read_excel('test_bag.xlsx')))
df_test_tweet_stemmer = one_hot(dataframe_full_text(pd.read_excel('test_bag_stemmer.xlsx')))

# Test 01

In [ ]:
# Create vectors https://github.com/amaiya/ktrain/blob/master/ktrain/text/data.py
# random_state = 42, so that every time that the algorithm is run it leads to the same results
# high number of max_features - the entire corpus was included
# the maxlen was not a huge concern - tweets are short (limited by characters)

(x_train_00, y_train_00), (x_test_sentence, y_test_sentence), preproc = text.texts_from_df(df_train, text_column = 'sentence',
                                                                                      label_columns=['01','02','03','04','05'],
                                                                                      maxlen=64, 
                                                                                      max_features = 3000,
                                                                                      preprocess_mode = 'standard',
                                                                                      lang = None,
                                                                                      ngram_range=1,
                                                                                      val_df = df_test_sentence,
                                                                                      random_state = 42
                                                                                      )

language: pt
Word Counts: 2413
Nrows: 1170
1170 train sequences
train sequence lengths:
	mean : 6
	95percentile : 16
	99percentile : 23
x_train shape: (1170,64)
y_train shape: (1170, 5)
Is Multi-Label? False
218 test sequences
test sequence lengths:
	mean : 3
	95percentile : 9
	99percentile : 16
x_test shape: (218,64)
y_test shape: (218, 5)


In [ ]:
learn_bag_test_01 = ktrain.get_learner(text.text_classifier('nbsvm', (x_train_00, y_train_00) , preproc=preproc), 
                             train_data=(x_train_00, y_train_00), 
                             val_data=(x_test_sentence, y_test_sentence), batch_size = 10
                             )

Is Multi-Label? False
compiling word ID features...
maxlen is 64
building document-term matrix... this may take a few moments...
rows: 1-1170
computing log-count ratios...
done.


In [ ]:
learn_bag_test_01.fit_onecycle(0.01,20)



begin training using onecycle policy with max lr of 0.01...
Epoch 1/20
234/234 [==============================] - 1s 2ms/step - loss: 1.5319 - accuracy: 0.3060 - val_loss: nan - val_accuracy: 0.1514
Epoch 2/20
234/234 [==============================] - 0s 2ms/step - loss: 1.3507 - accuracy: 0.4427 - val_loss: nan - val_accuracy: 0.1606
Epoch 3/20
234/234 [==============================] - 0s 2ms/step - loss: 1.2130 - accuracy: 0.4974 - val_loss: nan - val_accuracy: 0.1697
Epoch 4/20
234/234 [==============================] - 0s 2ms/step - loss: 1.1195 - accuracy: 0.5222 - val_loss: nan - val_accuracy: 0.1927
Epoch 5/20
234/234 [==============================] - 0s 2ms/step - loss: 1.0489 - accuracy: 0.5598 - val_loss: nan - val_accuracy: 0.1881
Epoch 6/20
234/234 [==============================] - 0s 2ms/step - loss: 0.9946 - accuracy: 0.5769 - val_loss: nan - val_accuracy: 0.1927
Epoch 7/20
234/234 [==============================] - 0s 2ms/step - loss: 0.9496 - accuracy: 0.5940 - va

In [ ]:
learn_bag_test_01.validate()

              precision    recall  f1-score   support

           0       1.00      0.20      0.34       218
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0

    accuracy                           0.20       218
   macro avg       0.20      0.04      0.07       218
weighted avg       1.00      0.20      0.34       218



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[44, 55, 36, 53, 30],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

# Test 02

In [ ]:
(x_train_01, y_train_01), (x_test_tweet, y_test_tweet), preproc01 = text.texts_from_df(df_train, text_column='sentence',
                                                                                    label_columns=['01','02','03','04','05'],
                                                                                    maxlen=64, 
                                                                                    max_features=3000,
                                                                                    preprocess_mode='standard',
                                                                                    lang=None,
                                                                                    ngram_range=1,
                                                                                    val_df = df_test_tweet,
                                                                                    random_state = 42
                                                                                    )

learn_bag_test_02 = ktrain.get_learner(text.text_classifier('nbsvm', (x_train_01, y_train_01) , preproc=preproc01), 
                                train_data=(x_train_01, y_train_01), 
                                val_data=(x_test_tweet, y_test_tweet), batch_size = 10
                                )

learn_bag_test_02.fit_onecycle(0.01,20)

learn_bag_test_02.validate()

language: pt
Word Counts: 2413
Nrows: 1170
1170 train sequences
train sequence lengths:
	mean : 6
	95percentile : 16
	99percentile : 23
x_train shape: (1170,64)
y_train shape: (1170, 5)
Is Multi-Label? False
218 test sequences
test sequence lengths:
	mean : 8
	95percentile : 17
	99percentile : 24
x_test shape: (218,64)
y_test shape: (218, 5)
Is Multi-Label? False
compiling word ID features...
maxlen is 64
building document-term matrix... this may take a few moments...
rows: 1-1170
computing log-count ratios...
done.


begin training using onecycle policy with max lr of 0.01...
Epoch 1/20
117/117 [==============================] - 0s 3ms/step - loss: 1.5419 - accuracy: 0.3000 - val_loss: 1.3060 - val_accuracy: 0.6881
Epoch 2/20
117/117 [==============================] - 0s 2ms/step - loss: 1.3996 - accuracy: 0.4402 - val_loss: 1.0609 - val_accuracy: 0.7294
Epoch 3/20
117/117 [==============================] - 0s 2ms/step - loss: 1.2709 - accuracy: 0.4769 - val_loss: 0.9071 - val_accurac

array([[ 1,  0,  0,  0,  0],
       [ 8, 56,  2, 14,  0],
       [ 1,  2,  7,  6,  1],
       [10,  8, 11, 54, 12],
       [ 0,  2,  1,  5, 17]])

# Test 03

In [ ]:
(x_train_stemmer_00, y_train_stemmer_00), (x_test_sentence_stemmer, y_test_sentence_stemmer), preproc_stemmer_00 = text.texts_from_df(df_train_stemmer, text_column='sentence',
                                                                                                                                    label_columns=['01','02','03','04','05'],
                                                                                                                                    maxlen=64, 
                                                                                                                                    max_features=1000,
                                                                                                                                    preprocess_mode='standard',
                                                                                                                                    lang='pt',
                                                                                                                                    ngram_range=1,
                                                                                                                                    val_df = df_test_sentence_stemmer,
                                                                                                                                    random_state = 42
                                                                                                                                    )
learn_bag_test_03 = ktrain.get_learner(text.text_classifier('nbsvm', (x_train_stemmer_00, y_train_stemmer_00) , preproc=preproc_stemmer_00), 
                                                          train_data=(x_train_stemmer_00, y_train_stemmer_00), 
                                                          val_data=(x_test_sentence_stemmer, y_test_sentence_stemmer), batch_size = 10
                                                          )

learn_bag_test_03.fit_onecycle(0.01,20)

learn_bag_test_03.validate()

language: pt
Word Counts: 1852
Nrows: 1170
1170 train sequences
train sequence lengths:
	mean : 5
	95percentile : 15
	99percentile : 22
x_train shape: (1170,64)
y_train shape: (1170, 5)
Is Multi-Label? False
218 test sequences
test sequence lengths:
	mean : 4
	95percentile : 10
	99percentile : 16
x_test shape: (218,64)
y_test shape: (218, 5)
Is Multi-Label? False
compiling word ID features...
maxlen is 64
building document-term matrix... this may take a few moments...
rows: 1-1170
computing log-count ratios...
done.


begin training using onecycle policy with max lr of 0.01...
Epoch 1/20
117/117 [==============================] - 0s 3ms/step - loss: 1.5593 - accuracy: 0.2744 - val_loss: nan - val_accuracy: 0.2248
Epoch 2/20
117/117 [==============================] - 0s 2ms/step - loss: 1.4084 - accuracy: 0.4299 - val_loss: nan - val_accuracy: 0.1468
Epoch 3/20
117/117 [==============================] - 0s 2ms/step - loss: 1.2762 - accuracy: 0.4692 - val_loss: nan - val_accuracy: 0.1376

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[34, 68, 26, 59, 31],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

# Test 04

In [ ]:
(x_train_stemmer_01, y_train_stemmer_01), (x_test_tweet_stemmer, y_test_tweet_stemmer), preproc_stemmer_01 = text.texts_from_df(df_train_stemmer, text_column='sentence',
                                                                                                                              label_columns=['01','02','03','04','05'],
                                                                                                                              maxlen=64, 
                                                                                                                              max_features=1000,
                                                                                                                              preprocess_mode='standard',
                                                                                                                              lang='pt',
                                                                                                                              ngram_range=1,
                                                                                                                              val_df = df_test_tweet_stemmer,
                                                                                                                              random_state = 42
                                                                                                                             )

learn_bag_test_04 = ktrain.get_learner(text.text_classifier('nbsvm', (x_train_stemmer_01, y_train_stemmer_01) , preproc=preproc_stemmer_01), 
                                    train_data=(x_train_stemmer_01, y_train_stemmer_01), 
                                    val_data=(x_test_tweet_stemmer, y_test_tweet_stemmer), batch_size = 10
                                    )

learn_bag_test_04.fit_onecycle(0.01,20)

learn_bag_test_04.validate()

language: pt
Word Counts: 1852
Nrows: 1170
1170 train sequences
train sequence lengths:
	mean : 5
	95percentile : 15
	99percentile : 22
x_train shape: (1170,64)
y_train shape: (1170, 5)
Is Multi-Label? False
218 test sequences
test sequence lengths:
	mean : 8
	95percentile : 19
	99percentile : 26
x_test shape: (218,64)
y_test shape: (218, 5)
Is Multi-Label? False
compiling word ID features...
maxlen is 64
building document-term matrix... this may take a few moments...
rows: 1-1170
computing log-count ratios...
done.


begin training using onecycle policy with max lr of 0.01...
Epoch 1/20
117/117 [==============================] - 0s 3ms/step - loss: 1.5489 - accuracy: 0.2846 - val_loss: 1.2600 - val_accuracy: 0.6743
Epoch 2/20
117/117 [==============================] - 0s 2ms/step - loss: 1.4013 - accuracy: 0.4188 - val_loss: 1.0192 - val_accuracy: 0.7294
Epoch 3/20
117/117 [==============================] - 0s 2ms/step - loss: 1.2748 - accuracy: 0.4744 - val_loss: 0.8838 - val_accurac

array([[ 1,  0,  0,  0,  0],
       [ 5, 59,  2, 14,  0],
       [ 1,  3,  5,  8,  0],
       [ 6,  9,  6, 67,  7],
       [ 0,  2,  0,  4, 19]])